export const SET_ALERT = 'SET_ALERT'
export const UNSET_ALERT = 'UNSET_ALERT'
export const DISPLAY_LOADING_SPINNER = 'DISPLAY_LOADING_SPINNER'
export const HIDE_LOADING_SPINNER = 'HIDE_LOADING_SPINNER'
